using System;
using System.IO;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System.Text.RegularExpressions;
using GlobalsNS;
using MenuCustomNS;


namespace MenuCustomNS
{
    public class EuroCupTeams
    {
        /*team name 
         * gk 
         * shot 
         * index 
         * coinsNeeded 
         * fans/flag color number
         * thirt color 
         * shorts color
         * sock color
         * thirt number color
         * hair
         * flare color
         */
        private string[][] teams = new string[][] {
             new string[] {
                "Bosnia",
                "60",
                "58",
                "0",
                "0",
                "blue|blue|bosnia",
                 "bluewithwhiteshirt",
                "darkbluewhitestripes",
                "darkbluewhitestripessocks",
                "skin_white_1",
                "hair_19",
                "blue",
                "Klaus:Chile:60:58:U:0:f0_s2_b0_t0_hblack4",
                "shoeblue|shoebluewhite",
                "glovebluewhite"},
             new string[] {
                "Estonia",
                "43",
                "42",
                "0",
                "0",
                "blue|blue|estonia",
                 "blueshirt", "black", "white",
                "skin_white_1", "hair_16", "blue",
                "Klaus:Chile:43:42:U:0:f4_s2_b2_t9_hblack2",
                 "shoebluewhite|shoeblackred",
                 "gloveblacblue|glovebluewhite"},
             new string[] {
                 "Georgia",
                 "51", 
                 "53",
                 "0",
                 "0",
                 "red|red|georgia",
                 "whiteshirt", "redwhitestripesshort", "white",
                "skin_white_1", "hair_16", "red",
                 "Klaus:Chile:51:53:U:0:f2_s1_b2_t8_hblack8",
                 "shoeblackred|shoeredwhite",
                 "gloveredwhite"},           
             new string[] {
                 "Latvia",
                 "43", 
                 "41",
                 "0",
                 "0",
                "red|red|latvia",
                 "darkredshirt", "whiteredstripesshort", "darkredgreystripesocks",
                "skin_white_1", "hair_16", "red",
                 "Klaus:Chile:85:65:U:0:f4_s2_b0_t0_hblonde4",
                 "shoewhite|shoeredwhite",
                 "gloveredwhite"},
             new string[] {
                 "Lithuania",
                 "43", 
                 "44",
                 "0",
                 "0",
                 "yellow|green|lithuania",
                 "yellowwithgreenshirt", "greenshorts", "yellowsocks",
                "skin_white_1", "hair_19", "yellow",
                 "Klaus:Chile:85:65:U:0:f5_s2_b0_t0_hblack3",
                 "shoeyellow|shoegreen",
                 "glovegreenwhite|gloveyellow|gloveyellowwhite"},
             new string[] {
                 "Montenegro",
                 "51", 
                 "49",
                 "0",
                 "0",
                 "red|red|montenegro",
                 "redshirt", "redshort", "sock_red",
                "skin_white_1", "hair_4", "red",
                 "Klaus:Chile:85:65:U:0:f6_s3_b2_t10_hblack8",
                 "shoeredwhite|shoeblackred",
                 "gloveredwhite"},            
             new string[] {
                 "Serbia",
                 "63", 
                 "67",
                 "0",
                 "0",
                 "red|red|serbia",
                "redwithwhiteshirt", "redshort", "sock_red",
                "skin_white_1", "hair_8", "red",
                 "Klaus:Chile:85:65:U:0:f8_s3_b0_t0_hblack5",
                 "shoered|shoeredwhite",
                 "gloveredwhite"},
             new string[] {
                 "Slovakia",
                 "63", 
                 "61",
                 "0",
                 "0",
                 "blue|blue|slovakia",
                "whiteshirt", "whiteshort", "whitebluestripesocks",
                "skin_white_1", "hair_8", "blue",
                 "Klaus:Chile:85:65:U:0:f9_s1_b0_t0_hblack10",
                 "shoebluewhite",
                 "glovebluewhite"},
             new string[] {
                 "Slovenia",
                 "58", 
                 "53",
                 "0",
                 "0",
                 "blue|blue|slovenia",
                "bluewhireshirt", "whiteshort", "whiteblueblackstripessocks",
                "skin_white_1", "hair_8", "blue",
                 "Klaus:Chile:85:65:U:0:f0_s1_b0_t0_hblack9",
                 "shoeblue",
                 "glovebluewhite"},                                                                               
            new string[] {
                "Austria",
                "68", 
                "64",
                "5",
                "840",
                "red|red|austria",
                "redshirt", "whiteshort", "sock_red", "skin_white_4", "hair_8", "red",
                "Klaus:Chile:85:65:U:0:f0_s2_b2_t4_hred3",
                "shoeblackred|shoeredwhite",
                "gloveredwhite"},
            new string[] {
                "Denmark",
                "75",
                "69",
                "6",
                "4810",
                "red|red|denmark",
                "redshirt",
                "whiteredstripeshort",
                "redwhitestripesocks1",
                "skin_white_5",
                "hair_1",
                "red",
                "Klaus:Chile:85:65:U:0:f1_s2_b0_t0_hblonde6",
                "shoeredwhite",
                "gloveredwhite"},
            new string[] {
                "Germany",
                "93", 
                "87",
                "7",
                "9210",
                "white|black|germany",
                "whiteblackstripeshorshirt",
                "blackwhitestripesshort",
                "whiteblacstripessocks",
                "skin_white_6",
                "hair_8",
                "white",
                "Klaus:Chile:85:65:U:0:f9_s1_b0_t0_hblack7",
                "shoeblue|shoeblack",
                "globewhiteblack|gloveblackwhite"},
            new string[] {
                "Greece",
                "59", 
                "65",
                "8",
                "0",
                "blue|blue|greece",
                "bluewithwhiteshirt",
                "darkbluewhitestripes",
                "whitebluestripesocks",
                "skin_white_7",
                "hair_9",
                "blue",
                "Klaus:Chile:85:65:U:0:f0_s1_b2_t2_hblack6",
                "shoewhiteblack",
                "glovebluewhite"},
            new string[] {
                "France",
                "95", 
                "95",
                "9",
                "9500",
                "blue|blue|france",
                "darkbluedarkbluestripesshirt",
                "darkblueshort1",
                "sock_red",
                "skin_white_8",
                "hair_10",
                "blue",
                "Klaus:Chile:85:65:U:0:f1_s1_b0_t0_hblack5",
                "shoeredwhite|shoeblackred",
                "gloveblacblue|glovebluewhite"},
            new string[] {
                "Finland",
                "49", 
                "56",
                "10",
                "0",
                "blue|blue|finland",
                "whiteblestripevertshirt", "whiteshort", "white", "skin_white_9", "hair_22", "white",
                "Klaus:Chile:85:65:U:0:f2_s2_b0_t0_hblonde3",
                "shoebluewhite|shoeblue",
                "glovebluewhite"},
            new string[] {
                "Hungary",
                "61", 
                "58",
                "11",
                "5",
                "red|red|hungary",
                "redwithwhiteshirt", "whiteredstripeshort", "greenwhitestripessocks", "skin_white_10", "hair_11", "red",
                "Klaus:Chile:85:65:U:0:f3_s2_b0_t0_hblack4",
                "shoegreen",
                "glovegreenwhite|gloveredwhite"},
            new string[] {
                "Iceland",
                "65", 
                "63",
                "12",
                "3410",
                "blue|blue|iceland",
                "blueshirt", "darkblueshort11", "darkblue", "skin_white_11", "hair_24", "blue",
                "Klaus:Chile:85:65:U:0:f4_s2_b2_t9_hblonde5",
                "shoebluewhite",
                "glovebluewhite"},
            new string[] {
                "Italy",
                "83", 
                "82",
                "13",
                "8510",
                "blue|blue|italy",
                "blueshirt", "whitebluestripeshort", "darkblue", "skin_white_12", "hair_12", "blue",
                "Klaus:Chile:85:65:U:0:f5_s1_b0_t0_hblack11",
                "shoeblue|shoebluewhite",
                "glovebluewhite"},
            new string[] {
                "Netherlands",
                "80", 
                "83",
                "14",
                "7232",
                "orange|yellowblue|netherlands",
                ///"orange|orange|netherlands",
                "orangeblackstripesshirt", "whiteshort", "orangeblackstripesocks", "skin_white_13", "hair_25",
                "yellow",
                "Klaus:Chile:85:65:U:0:f6_s3_b2_t10_hblonde4",
                "shoeorange",
                "gloveblackorange"},
            new string[] {
                "Poland",
                "71", 
                "81",
                "15",
                "0",
                "red|poland|poland",
                "whiteredshirt", "redshort", "white", "skin_white_16", "hair_19", "red",
                "Klaus:Chile:85:65:U:0:f7_s1_b0_t0_hblack10",
                "shoeredwhite|shoered",
                "gloveredwhite"},
            new string[] {
                "Belgium",
                "85", 
                "87",
                "16",
                "6500",
                "red|red|belgium",
                "redblackstripesshirt", "redblackstripesshort", "redblackstripessocks", "skin_white_15", "hair_19", "red",
                "Klaus:Chile:85:65:U:0:f8_s3_b0_t0_hblack11",
                "shoeblackred|shoered",
                "gloveredwhite|gloveredblack"},
            new string[] {
                "Portugal",
                "85", 
                "87",
                "17",
                "5542",
                "red|red|portugal",
                "darkredshirt", "greenshorts", "redblackstripessocks", "skin_white_16", "hair_15", "red",
                "Klaus:Chile:85:65:U:0:f9_s1_b0_t0_hblack10",
                "shoeblackred|shoegreen",
                "gloveredblack|gloveredwhite|gloveblackgreen"},
            new string[] {
                "Croatia",
                "85", 
                "87",
                "18",
                "7500",
                "red|red|croatia",
                "croatiashirt", "whiteblueshort", "white", "skin_white_17", "hair_16", "red",
                "Klaus:Chile:85:65:U:0:f0_s1_b2_t2_hblack4",
                "shoeredwhite|shoered",
                "gloveredwhite"},
            new string[] {
                "Spain",
                "85", 
                "85",
                "19",
                "9995",
                "red|red|spain",
                "darkredwithyellowshirt", "darkblueyellowstripeshort", "darkblueyellowstripessocks", "skin_white_18", "hair_17", "red",
                "Klaus:Chile:85:65:U:0:f1_s1_b0_t0_hblack13",
                "shoeyellow|shoered",
                "gloveyellowblack|gloveblacblue|gloveblueyellow"},          
            new string[] {
                "Switzerland",
                "77", 
                "79",
                "21",
                "5300",
                "red|red|switzerland",
                "redshirt", "whiteshort", "sock_red", "skin_white_20", "hair_19", "red",
                "Klaus:Chile:85:65:U:0:f3_s2_b2_t5_hblack5",
                "shoeredwhite|shoered",
                "gloveredwhite"},
            new string[] {
                "Sweden",
                "71", 
                "68",
                "22",
                "4100",
                "yellow|yellowblue|sweden",
                "yellowbluestripesshirt", "darkblueyellowstripeshort", "yellowbluestripecsocks", "skin_white_21", "hair_26", "yellow",
                "Klaus:Chile:85:65:U:0:f4_s2_b0_t0_hblonde1",
                "shoeblack|shoebluewhite",
                "gloveblueyellow|gloveyellowblack"},                                            
            new string[] {
                "Ukraine",
                "71", 
                "62",
                "27",
                "1760",
                "yellow|yellowblue|ukraine",
                "yellowbluestripesshirt1", "yellowshort", "yellowsocks", "skin_white_3", "hair_26", "yellow",
                "Klaus:Chile:85:65:U:0:f9_s3_b0_t0_hblonde2",
                "shoeyellow|shoeblack",
                "gloveyellow|gloveyellowblack"},
            new string[] {
                "Romania",
                "59",
                "59",
                "28",
                "250",
                "yellow|yellowblue|romania",
                "yellowbluestripeshirt", "yellowredstripesshort", "yellowsocks",
                "skin_white_3", "hair_23", "yellow",
                "Klaus:Chile:85:65:U:0:f0_s1_b2_t2_hblack5",
                "shoeblue|shoeblack",
                "gloveyellow|gloveyellowblack"},                              
            new string[] {
                "Turkey",
                "63", 
                "56",
                "32",
                "2300",
                "red|red|turkey",
                "redshirt", "redshort", "white", "skin_white_2", "hair_12", "red",
                "Klaus:Chile:63:56:U:0:f4_s1_b0_t0_hblack5",
                "shoeredwhite|shoered",
                "gloveredwhite"},
            new string[] {
                "Czechia",
                "63", 
                "61",
                "33",
                "0",
                "red|red|czechia",
                "redshirt", "darkblueshort11", "sock_red",
                "skin_white_3", "hair_19", "red",
                "Klaus:Chile:63:61:U:0:f5_s2_b0_t0_hblonde5",
                "shoeblue|shoebluewhite",
                "glovebluewhite|glovebluered"},            
            new string[] {
                "Russia",
                "64", 
                "67",
                "35",
                "1190",
                "red|red|russia",
                "redwithwhiteshirt", "whiteredstripesshort", "redwhitesocks", "skin_white_6", "hair_28", "red",
                "Klaus:Chile:85:65:U:0:f7_s1_b0_t0_hred4",
                "shoeredwhite",
                "gloveredwhite"},
            new string[] {
                "Bulgaria",
                "59", 
                "49",
                "36",
                "0",
                "green|green|bulgaria",
                "whitewithgreenstripeshirt", "greenshorts", "whiteredsocks", "skin_white_7", "hair_23", "green",
                "Klaus:Chile:85:65:U:0:f5_s1_b0_t0_hblack4",
                "shoegreen",
                "glovegreenwhite|gloveblackgreen"},                                                                                  
            new string[] {
                "England",
                "87", 
                "85",
                "48",
                "6130",
                "white|red|england",
                "whiteblueshirt", "darkblueredstropedn", "whiteredstripessocks1",
                "skin_white_16", "hair_16", "white",
                "Klaus:Chile:85:65:U:0:f0_s2_b0_t0_hred4",
                "shoeredwhite|shoebluewhite",
                "glovebluewhite"},                     
            new string[] {
                "Norway",
                "51", 
                "52",
                "51",
                "0",
                "red|red|norway",
                "redblueshirt1", "whiteshort", "blueredstripedownsocks",
                "skin_white_21", "hair_1", "red",
                "Klaus:Chile:85:65:U:0:f3_s2_b0_t0_hblonde5",
                "shoebluewhite|shoeredwhite",
                "gloveredwhite"},                             
            new string[] {
                "Albania",
                "55",
                "56",
                "56",
                "0",
                "red|red|albania",
                "redwithblackshirt", "black", "sock_red",
                "skin_white_20", "hair_15", "red",
                "Klaus:Chile:85:65:U:0:f7_s1_b0_t0_hblack4",
                "shoeblackred|shoeredwhite",
                "gloveredblack"},           
            new string[] {
                "Belarus",
                "45", 
                "43",
                "58",
                "0",
                "red|red|belarus",
                "whiteshirt", "whiteshort", "white",
                "skin_white_18", "hair_24", "red",
                "Klaus:Chile:85:65:U:0:f9_s3_b2_t7_hblonde3",
                "shoeblue|shoered",
                "globewhiteblack"},
            new string[] {
                "Ireland",
                "53",
                "52",
                "59",
                "0",
                "green|green|ireland",
                "greenshirt1", "greenshorts", "greensocks",
                "skin_white_17", "hair_8", "green",
                "Klaus:Chile:85:65:U:0:f0_s2_b0_t0_hblack10",
                "shoegreen",
                "glovegreenwhite|gloveblackgreen"},
            new string[] {
                "Israel",
                "45", 
                "43",
                "60",
                "0",
                "blue|blue|israel",
                "whiteshirt", "lightblueshort", "white",
                "skin_white_16", "hair_10", "blue",
                "Klaus:Chile:85:65:U:0:f1_s2_b0_t0_hblack4",
                "shoeblue",
                "gloveblueblue|glovebluewhite"},           
             new string[] {
                 "Kazakhstan",
                 "48",
                 "50",
                 "2",
                 "0",
                 "yellow|yellowblue|kazakhstan",
                 "yellowbluestripesshirt", "yellowbluestripesshort", "yellowbluestripecsocks", "skin_white_16", "hair_25", "yellow",
                 "Klaus:Chile:85:65:U:0:f4_s2_b2_t9_hblonde4",
                 "shoeblue|shoeyellow",
                 "gloveblueyellow|gloveyellow"},
             new string[] {
                 "San Marino",
                 "39", 
                 "40",
                 "2",
                 "0",
                 "blue|blue|sanmarino",
                "lightbluestripes", "lightblueshort", "bluewhitestripedownsocks", "skin_white_18", "hair_23", "blue",
                 "Klaus:Chile:85:65:U:0:f4_s1_b0_t0_hblack7",
                 "shoeblue",
                 "gloveblueblue|glovelightbluewhite"},            
             new string[] {
                 "Scotland",
                 "63", 
                 "60",
                 "13",
                 "0",
                 "blue|blue|scotland",
                "bluewithwhiteshirt", "darkbluewhitestripes", "darkbluewhitestripessocks", "skin_white_12", "hair_12", "blue",
                 "Klaus:Chile:85:65:U:0:f5_s2_b0_t0_hred2",
                 "shoebluewhite",
                 "glovebluewhite"},
             new string[] {
                 "Wales",
                 "73", 
                 "74",
                 "19",
                 "0",
                 "red|red|wales",
                "redshirt", "redyellowstripeshort", "redyellowstripessocks", "skin_white_18", "hair_17", "red",
                 "Klaus:Chile:85:65:U:0:f6_s3_b2_t10_hblack8",
                 "shoeredwhite|shoeblackred",
                 "gloveredwhite"},
             new string[] {
                 "Armenia",
                 "50", 
                 "49",
                 "19",
                 "0",
                 "red|red|armenia",
                "darkredshirt", "darkredshort", "darkredgreystripesocks", "skin_white_18", "hair_28", "red",
                 "Klaus:Chile:85:65:U:0:f7_s1_b0_t0_hblack4",
                 "shoered",
                 "gloveredwhite"},
             new string[] {
                 "Cyprus",
                 "50", 
                 "49",
                 "19",
                 "0",
                 "blue|blue|cyprus",
               "blueshirt", "darkblueshort11", "darkblue", "skin_white_18", "hair_10", "blue",
                 "Klaus:Chile:85:65:U:0:f8_s1_b0_t0_hblack5",
                 "shoebluewhite",
                 "glovebluewhite"},
             new string[] {
                 "Northern Ireland",
                 "55", 
                 "54",
                 "0",
                 "0",
                 "green|green|northernireland",
                "greenshirt1", "whitegreenstripesshort", "greenwhitestripessocks",
                "skin_white_1", "hair_5", "green",
                 "Klaus:Chile:85:65:U:0:f9_s3_b0_t0_hblack6",
                 "shoegreen",
                 "gloveyellow|gloveblackgreen"}
        };

        public string[][] getTeams()
        {
            return teams;
        }        
    }
}
